package cl.cognus.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.9
 * 2013-09-15T20:44:24.491-04:00
 * Generated source version: 2.6.9
 * 
 */
@WebService(targetNamespace = "http://ws.cognus.cl/", name = "ConsultasAfiliados")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultasAfiliados {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaTrabajador", targetNamespace = "http://ws.cognus.cl/", className = "cl.cognus.ws.ConsultaTrabajador")
    @WebMethod
    @ResponseWrapper(localName = "consultaTrabajadorResponse", targetNamespace = "http://ws.cognus.cl/", className = "cl.cognus.ws.ConsultaTrabajadorResponse")
    public cl.cognus.ws.TrabajadoresResponse consultaTrabajador(
        @WebParam(name = "rut", targetNamespace = "")
        java.lang.String rut,
        @WebParam(name = "periodo", targetNamespace = "")
        int periodo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaEmpresa", targetNamespace = "http://ws.cognus.cl/", className = "cl.cognus.ws.ConsultaEmpresa")
    @WebMethod
    @ResponseWrapper(localName = "consultaEmpresaResponse", targetNamespace = "http://ws.cognus.cl/", className = "cl.cognus.ws.ConsultaEmpresaResponse")
    public cl.cognus.ws.EmpresaResponse consultaEmpresa(
        @WebParam(name = "rut", targetNamespace = "")
        java.lang.String rut,
        @WebParam(name = "periodo", targetNamespace = "")
        int periodo
    );
}
