package cl.adexus.isl.spm

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
				
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true

				//API no authenticated by ajunge
				if( controllerName=="jaxrs") return true
				
				//Calendario no autenticado
				if (controllerName=="calendar") return true
				
                // Access control by convention.
                accessControl()
            }
        }
    }
}
